guardrails hub install hub://guardrails/regex_match
guardrails hub install hub://guardrails/valid_length
guardrails hub install hub://guardrails/ends_with
guardrails hub install hub://guardrails/contains_string
guardrails hub install hub://guardrails/competitor_check
guardrails hub install hub://guardrails/detect_pii
guardrails hub install hub://guardrails/gibberish_text
guardrails hub install hub://guardrails/nsfw_text
guardrails hub install hub://guardrails/secrets_present
guardrails hub install hub://guardrails/toxic_language
guardrails hub install hub://cartesia/financial_tone
guardrails hub install hub://groundedai/grounded_ai_hallucination
guardrails hub install hub://guardrails/guardrails_pii
guardrails hub install hub://guardrails/has_url
guardrails hub install hub://guardrails/lowercase
guardrails hub install hub://cartesia/mentions_drugs
guardrails hub install hub://guardrails/one_line
guardrails hub install hub://guardrails/redundant_sentences
guardrails hub install hub://reflex/valid_python